spring:
  profiles:
    active: dev
  application:
    name: trading-api
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          fetch_size: 50
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  tomcat:
    max-threads: 200
    accept-count: 100
    max-connections: 8192

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

